const rugs = [
    {
        name: "Heriz Rug",
        location: "New York, NY",
        description: "Turkish Rug",
        rating: 10,
        price: 895,
        quantity: 10,
        photo: "/Images/heriz.jpeg",
        isFeatured: true,
    },
    {
        name: "Kashan",
        location: "Laguna, CA",
        description: "Moroccan Rug",
        rating: 7,
        price: 740,
        quantity: 6,
        photo: "/Images/kashan.jpeg",
        isFeatured: false,
    },
    {
        name: "Nian Rug",
        location: "Denver, CO",
        description: "Persian Rug",
        rating: 9,
        price: 1100,
        quantity: 2,
        photo: "/Images/nilan.jpeg",
        isFeatured: false,
    },
    {
        name: "Bijar",
        location: "New York, NY",
        description: "Moroccan Rug",
        rating: 10,
        price: 1000,
        quantity: 0,
        photo: "/Images/bijar.jpeg",
        isFeatured: false,
    },
    {
        name: "Tabriz",
        location: "New York, NY",
        description: "Turkish Rug",
        rating: 10,
        price: 1200,
        quantity: 3,
        photo: "/Images/tabriz.jpeg",
        isFeatured: true,
    },
    {
        name: "Gabbeh",
        location: "Laguna, CA",
        description: "Persian Rug",
        rating: 10,
        price: 1300,
        quantity: 1,
        photo: "/Images/gabbeh.jpeg",
        isFeatured: true,
    },
    {
        name: "Kilim",
        location: "Denver, CO",
        description: "Turkish Rug",
        rating: 7,
        price: 990,
        quantity: 5,
        photo: "/Images/kilim.jpeg",
        isFeatured: false,
    },
    {
        name: "Sanandaj",
        location: "New York, NY",
        description: "Moroccan Rug",
        rating: 7,
        price: 880,
        quantity: 3,
        photo: "/Images/sanandaj.jpeg",
        isFeatured: false,
    },
    {
        name: "Surya",
        location: "Denver, CO",
        description: "Persian Rug",
        rating: 5,
        price: 650,
        quantity: 8,
        photo: "/Images/surya.jpeg",
        isFeatured: false,
    }
]

// Export the seed data to `models/index.js`
module.exports = rugs
