const rugs = [
    {
        name: "Heriz Rug",
        location: "New York, NY",
        description: "Turkish Rug",
        Rating: 10,
        Price: 895,
        Quantity: 10,
        photo: "/Images/heriz.jpeg",
        isFeatured: true,
    },
    {
        name: "Kashan",
        location: "Laguna, CA",
        description: "Moroccan Rug",
        Rating: 7,
        Price: 740,
        Quantity: 6,
        photo: "/Images/kashan.jpeg",
        isFeatured: false,
    },
    {
        name: "Nian Rug",
        location: "Denver, CO",
        description: "Persian Rug",
        Rating: 9,
        Price: 1100,
        Quantity: 2,
        photo: "/Images/nilan.jpeg",
        isFeatured: false,
    },
    {
        name: "Bijar",
        location: "New York, NY",
        description: "Moroccan Rug",
        Rating: 10,
        Price: 1000,
        Quantity: 0,
        photo: "/Images/bijar.jpeg",
        isFeatured: false,
    },
    {
        name: "Tabriz",
        location: "New York, NY",
        description: "Turkish Rug",
        Rating: 10,
        Price: 1200,
        Quantity: 3,
        photo: "/Images/tabriz.jpeg",
        isFeatured: true,
    },
    {
        name: "Gabbeh",
        location: "Laguna, CA",
        description: "Persian Rug",
        Rating: 10,
        Price: 1300,
        Quantity: 1,
        photo: "/Images/gabbeh.jpeg",
        isFeatured: true,
    },
    {
        name: "Kilim",
        location: "Denver, CO",
        description: "Turkish Rug",
        Rating: 7,
        Price: 990,
        Quantity: 5,
        photo: "/Images/kilim.jpeg",
        isFeatured: false,
    },
    {
        name: "Sanandaj",
        location: "New York, NY",
        description: "Moroccan Rug",
        Rating: 7,
        Price: 880,
        Quantity: 3,
        photo: "/Images/sanandaj.jpeg",
        isFeatured: false,
    },
    {
        name: "Surya",
        location: "Denver, CO",
        description: "Persian Rug",
        Rating: 5,
        Price: 650,
        Quantity: 8,
        photo: "/Images/surya.jpeg",
        isFeatured: false,
    }
]

// Export the seed data to `models/index.js`
module.exports = rugs